CREATE TABLE minutes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    sensor VARCHAR(32),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature DECIMAL(4,1),
    PRIMARY KEY (id));

CREATE TABLE hours (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    sensor VARCHAR(32),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature DECIMAL(4,1),
    PRIMARY KEY (id));

CREATE TABLE days (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    sensor VARCHAR(32),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    min DECIMAL(4,1),
    avg DECIMAL(4,1),
    max DECIMAL(4,1),
    PRIMARY KEY (id));

CREATE TABLE alerts (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    type VARCHAR(32),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature DECIMAL(4,1),
    PRIMARY KEY (id));
